EXPERIMENT 2 - ECE 2112

In [1]:
# In this code, I will be experimenting with numerical python numpy.
# I will initiate the library using this syntax or code:

import numpy as np

In [2]:
# First Problem - NORMALIZATION PROBLEM
# In this problem, create a random 5 x 5 ndarray and store it to variable X. Normalize X. Save your normalized
# ndarray as X_normalized.npy


X = np.random.random((5,5)) # Creating a random 5x5 array using the given X variable in the assignment file

# Normalization function
def normalize(x): 
    Z = (x - x.mean()) / x.std() # This is the formula of normalization which is Z = (X - mean of x) / standard deviation which is represented by omega
    np.save('X_normalized.npy', Z) # This line saves the normalized array using the given filename from the assignment file
    print(np.load('X_normalized.npy')) # This line prints and shows (loads) the saved file

normalize(X) # using the function on array X

[[ 0.73113384 -1.38567312 -1.09675491  0.42050078  0.24617   ]
 [ 0.28364487 -1.09797022  0.15058791  1.64962547 -1.36677134]
 [ 0.34449269 -0.34192798  1.20213499  1.87578527  1.80779563]
 [ 0.11550386  1.20153004 -0.82663398 -0.21769144 -1.44398504]
 [-0.7975593   0.4315628  -0.9610942  -0.07911395 -0.84529265]]


In [3]:
# Second Problem - DIVISIBLE BY 3 PROBLEM
# Create the following 10 x 10 ndarray (represented in the assignment file) which are the squares of the first 100 positive integers.
# From this ndarray, determine all the elements that are divisible by 3. Save the result as div_by_3.npy

A = A = np.arange(1, 101).reshape(10, 10) ** 2
# Creating an array with elements from 1 - 100 (excluding 101 because it is the terminal) and then reshaping the array to be a 10x10
# and then squaring each element

#print (A) - I used this code to check the array

x = A[A % 3 == 0] # This code will help me determine the elements that are divisible by 3
# Every element from array A is checked whether the element would have a 0 remainder after using the modular operation

np.save("div_by_3.npy", x) # Saving the file as instructed in the assignment file

print(np.load("div_by_3.npy")) # Displays the elements divisible by 3 from the file

[   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]
